const currencyList = {
    eth : {name : 'Ethereum', symbol : 'ETH'},
    dash : {name: 'Dash', symbol : 'DASH'},
    btc: {name : 'Bitcoin', symbol : 'BTC'},
    xrp: {name : 'Ripple', symbol : 'XRP'},
    usdt: {name : 'Tether', symbol : 'USDT'},
    bch: {name : 'Bitcoin Cash', symbol : 'BCH'},
    ltc: {name : 'Litecoin', symbol : 'LTC'},
    eos: {name : 'EOS', symbol : 'EOS'},
    bnb: {name : 'Binance Coin', symbol : 'BNB'},
    bsv: {name : 'Bitcoin SV', symbol : 'BSV'},
    xtz: {name : 'Tezos', symbol : 'XTZ'},
    ada: {name : 'Cardano', symbol : 'ADA'},
    trx: {name : 'TRON', symbol : 'TRX'},
    xlm: {name : 'Stellar', symbol : 'XLM'},
    xmr: {name : 'Monero', symbol : 'XMR'},
    leo: {name : 'LEO Token', symbol : 'LEO'},
    atom: {name : 'Cosmos', symbol : 'ATOM'},
    okb: {name : 'OKB', symbol : 'OKB'},
    link: {name : 'ChainLink', symbol : 'LINK'},
    ht: {name : 'Huobi Token', symbol : 'HT'},
    neo: {name : 'NEO', symbol : 'NEO'},
    usdc: {name : 'USD Coin', symbol : 'USDC'},
    etc: {name : 'Ethereum Classic', symbol : 'ETC'},
    cro: {name : 'Crypto.com Coin', symbol : 'CRO'},
    miota: {name : 'IOTA', symbol : 'MIOTA'},
    mkr: {name : 'Maker', symbol : 'MKR'},
    vet: {name : 'VeChain', symbol : 'VET'},
    ont: {name : 'Ontology', symbol : 'ONT'},
    xem: {name : 'NEM', symbol : 'XEM'},
    doge: {name : 'Dogecoin', symbol : 'DOGE'},
    bat: {name : 'Basic Attention Token', symbol : 'BAT'},
    pax: {name : 'Paxos Standard', symbol : 'PAX'},
    zec: {name : 'Zcash', symbol : 'ZEC'},
    dcr: {name : 'Decred', symbol : 'DCR'},
    qtum: {name : 'Qtum', symbol : 'QTUM'},
    tusd: {name : 'TrueUSD', symbol : 'TUSD'},
    algo: {name : 'Algorand', symbol : 'ALGO'},
    rvn: {name : 'Ravencoin', symbol : 'RVN'},
    snx: {name : 'Synthetix Network Token', symbol : 'SNX'},
    hot: {name : 'Holo', symbol : 'HOT'},
    zrx: {name : '0x', symbol : 'ZRX'},
    btm: {name : 'Bytom', symbol : 'BTM'},
    rep: {name : 'Augur', symbol : 'REP'},
    ckb: {name : 'Nervos Network', symbol : 'CKB'},
    theta: {name : 'Theta Network', symbol : 'THETA'},
    seele: {name : 'Seele', symbol : 'SEELE'},
    btg: {name : 'Bitcoin Gold', symbol : 'BTG'},
    omg: {name : 'OmiseGO', symbol : 'OMG'},
    nano: {name : 'Nano', symbol : 'NANO'},
    waves: {name : 'Waves', symbol : 'WAVES'},
    kcs: {name : 'KuCoin Shares', symbol : 'KCS'},
    lsk: {name : 'Lisk', symbol : 'LSK'},
    dgb: {name : 'DigiByte', symbol : 'DGB'},
    vsys: {name : 'V.SYSTEMS', symbol : 'VSYS'},
    gt: {name : 'Gatechain Token', symbol : 'GT'},
    enj: {name : 'Enjin Coin', symbol : 'ENJ'},
    kmd: {name : 'Komodo', symbol : 'KMD'},
    sxp: {name : 'Swipe', symbol : 'SXP'},
    bcd: {name : 'Bitcoin Diamond', symbol : 'BCD'},
    mco: {name : 'MCO', symbol : 'MCO'},
    ftt: {name : 'FTX Token', symbol : 'FTT'},
    iost: {name : 'IOST', symbol : 'IOST'},
    btt: {name : 'BitTorrent', symbol : 'BTT'},
    icx: {name : 'ICON', symbol : 'ICX'},
    xvg: {name : 'Verge', symbol : 'XVG'},
    mona: {name : 'MonaCoin', symbol : 'MONA'},
    sc: {name : 'Siacoin', symbol : 'SC'},
    stx: {name : 'Blockstack', symbol : 'STX'},
    zen: {name : 'Horizen', symbol : 'ZEN'},
    bcn: {name : 'Bytecoin', symbol : 'BCN'},
    dx: {name : 'DxChain Token', symbol : 'DX'},
    nexo: {name : 'NEXO', symbol : 'NEXO'},
    luna: {name : 'Luna', symbol : 'LUNA'},
    nrg: {name : 'Energi', symbol : 'NRG'},
    hc: {name : 'HyperCash', symbol : 'HC'},
    ae: {name : 'Aeternity', symbol : 'AE'},
    zil: {name : 'Zilliqa', symbol : 'ZIL'},
    steem: {name : 'Steem', symbol : 'STEEM'},
    bts: {name : 'BitShares', symbol : 'BTS'},
    dai: {name : 'Dai', symbol : 'DAI'},
    lamb: {name : 'Lambda', symbol : 'LAMB'},
    ardr: {name : 'Ardor', symbol : 'ARDR'},
    matic: {name : 'Matic Network', symbol : 'MATIC'},
    mana: {name : 'Decentraland', symbol : 'MANA'},
    btmx: {name : 'Bitmax Token', symbol : 'BTMX'},
    tomo: {name : 'TomoChain', symbol : 'TOMO'},
    qnt: {name : 'Quant', symbol : 'QNT'},
    strat: {name : 'Stratis', symbol : 'STRAT'},
    maid: {name : 'MaidSafeCoin', symbol : 'MAID'},
    etn: {name : 'Electroneum', symbol : 'ETN'},
    dgd: {name : 'DigixDAO', symbol : 'DGD'},
    dgtx: {name : 'Digitex Futures Exchange', symbol : 'DGTX'},
    snt: {name : 'Status', symbol : 'SNT'},
    eng: {name : 'Enigma', symbol : 'ENG'},
    you: {name : 'YOU Chain', symbol : 'YOU'},
    knc: {name : 'Kyber Network', symbol : 'KNC'},
    gnt: {name : 'Golem', symbol : 'GNT'},
    crpt: {name : 'Crypterium', symbol : 'CRPT'},
    chz: {name : 'Chiliz', symbol : 'CHZ'},
    cel: {name : 'Celsius Network', symbol : 'CEL'},
    npxs: {name : 'Pundi X', symbol : 'NPXS'},
    grin: {name : 'Grin', symbol : 'GRIN'},
    solve: {name : 'Solve.Care', symbol : 'SOLVE'},
    xzc: {name : 'Zcoin', symbol : 'XZC'},
    nex: {name : 'Nash Exchange', symbol : 'NEX'},
    rlc: {name : 'iExec RLC', symbol : 'RLC'},
    rif: {name : 'RIF Token', symbol : 'RIF'},
    nmr: {name : 'Numeraire', symbol : 'NMR'},
    ycc: {name : 'Yuan Chain Coin', symbol : 'YCC'},
    beam: {name : 'BEAM', symbol : 'BEAM'},
    ren: {name : 'REN', symbol : 'REN'},
    etp: {name : 'Metaverse ETP', symbol : 'ETP'},
    gxc: {name : 'GXChain', symbol : 'GXC'},
    xmx: {name : 'XMax', symbol : 'XMX'},
    usdk: {name : 'USDK', symbol : 'USDK'},
    elf: {name : 'aelf', symbol : 'ELF'},
    rcn: {name : 'Ripio Credit Network', symbol : 'RCN'},
    hbar: {name : 'Hedera Hashgraph', symbol : 'HBAR'},
    ela: {name : 'Elastos', symbol : 'ELA'},
    tlos: {name : 'Telos', symbol : 'TLOS'},
    ftm: {name : 'Fantom', symbol : 'FTM'},
    mxm: {name : 'Maximine', symbol : 'MXM'},
    ark: {name : 'Ark', symbol : 'ARK'},
    lrc: {name : 'Loopring', symbol : 'LRC'},
    aion: {name : 'Aion', symbol : 'AION'},
    fct: {name : 'Factom', symbol : 'FCT'},
    r: {name : 'Revain', symbol : 'R'},
    win: {name : 'WINk', symbol : 'WIN'},
    zb: {name : 'ZB Token', symbol : 'ZB'},
    tnt: {name : 'Tierion', symbol : 'TNT'},
    one: {name : 'Harmony', symbol : 'ONE'},
    nuls: {name : 'Nuls', symbol : 'NULS'},
    fun: {name : 'FunFair', symbol : 'FUN'},
    tt: {name : 'ThunderCore', symbol : 'TT'},
    zt: {name : 'ZTCoin', symbol : 'ZT'},
    wan: {name : 'Wanchain', symbol : 'WAN'},
    loki: {name : 'Loki Network', symbol : 'LOKI'},
    divi: {name : 'Divi', symbol : 'DIVI'},
    rdd: {name : 'Reddcoin', symbol : 'RDD'},
    edc: {name : 'EDC Blockchain', symbol : 'EDC'},
    ignis: {name : 'Ignis', symbol : 'IGNIS'},
    waxp: {name : 'WAX', symbol : 'WAXP'},
    bnt: {name : 'Bancor Network Token', symbol : 'BNT'},
    nas: {name : 'Nebulas', symbol : 'NAS'},
    fet: {name : 'Fetch.AI', symbol : 'FET'},
    dag: {name : 'Constellation', symbol : 'DAG'},
    qash: {name : 'QASH', symbol : 'QASH'},
    brd: {name : 'Bread', symbol : 'BRD'},
    powr: {name : 'Power Ledger', symbol : 'POWR'},
    ltnx: {name : 'Litenero', symbol : 'LTNX'},
    iotx: {name : 'IoTeX', symbol : 'IOTX'},
    erd: {name : 'Elrond', symbol : 'ERD'},
    storj: {name : 'Storj', symbol : 'STORJ'},
    ant: {name : 'Aragon', symbol : 'ANT'},
    mtl: {name : 'Metal', symbol : 'MTL'},
    loom: {name : 'Loom Network', symbol : 'LOOM'},
    kava: {name : 'Kava', symbol : 'KAVA'},
    ppt: {name : 'Populous', symbol : 'PPT'},
    cos: {name : 'Contentos', symbol : 'COS'},
    bnk: {name : 'Bankera', symbol : 'BNK'},
    ocean: {name : 'Ocean Protocol', symbol : 'OCEAN'},
    celr: {name : 'Celer Network', symbol : 'CELR'},
    aoa: {name : 'Aurora', symbol : 'AOA'},
    gas: {name : 'Gas', symbol : 'GAS'},
    pivx: {name : 'PIVX', symbol : 'PIVX'},
    vitae: {name : 'Vitae', symbol : 'VITAE'},
    eurs: {name : 'STASIS EURO', symbol : 'EURS'},
    c20: {name : 'CRYPTO20', symbol : 'C20'},
    agi: {name : 'SingularityNET', symbol : 'AGI'},
    wxt: {name : 'Wirex', symbol : 'WXT'},
    dent: {name : 'Dent', symbol : 'DENT'},
    abt: {name : 'Arcblock', symbol : 'ABT'},
    gno: {name : 'Gnosis', symbol : 'GNO'},
    hyn: {name : 'Hyperion', symbol : 'HYN'},
    tel: {name : 'Telcoin', symbol : 'TEL'},
    rox: {name : 'Robotina', symbol : 'ROX'},
    cs: {name : 'CREDITS', symbol : 'CS'},
    lba: {name : 'Cred', symbol : 'LBA'},
    sys: {name : 'Syscoin', symbol : 'SYS'},
    kick: {name : 'KickToken', symbol : 'KICK'},
    cvc: {name : 'Civic', symbol : 'CVC'},
    grs: {name : 'Groestlcoin', symbol : 'GRS'},
    nkn: {name : 'NKN', symbol : 'NKN'},
    cnd: {name : 'Cindicator', symbol : 'CND'},
    gbyte: {name : 'Obyte', symbol : 'GBYTE'},
    cocos: {name : 'COCOS BCX', symbol : 'COCOS'},
    susd: {name : 'sUSD', symbol : 'SUSD'},
    wtc: {name : 'Waltonchain', symbol : 'WTC'},
    qkc: {name : 'QuarkChain', symbol : 'QKC'},
    lend: {name : 'Aave', symbol : 'LEND'},
    oto: {name : 'OTOCASH', symbol : 'OTO'},
    go: {name : 'GoChain', symbol : 'GO'},
    nxs: {name : 'Nexus', symbol : 'NXS'},
    dusk: {name : 'DUSK Network', symbol : 'DUSK'},
    poly: {name : 'Polymath Network', symbol : 'POLY'},
    vtho: {name : 'VeThor Token', symbol : 'VTHO'},
    bix: {name : 'Bibox Token', symbol : 'BIX'},
    karma: {name : 'KARMA Coin', symbol : 'KARMA'},
    data: {name : 'Streamr DATAcoin', symbol : 'DATA'},
    ult: {name : 'Ultiledger', symbol : 'ULT'}
}

export default currencyList;